_wandb:
    value:
        cli_version: 0.22.3
        e:
            bi1106mju8aty3v0emtdl21aw9krni53:
                codePath: c:\Users\Christine\Documents\Python\Speciale_Kode\Deep learners\GRU\GRU multivariate cyclic DK1 copy.ipynb
                codePathLocal: GRU multivariate cyclic DK1 copy.ipynb
                cpu_count: 4
                cpu_count_logical: 8
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "999313895424"
                        used: "381016256512"
                email: chrso19@student.sdu.dk
                executable: c:\Users\Christine\anaconda3\envs\ds809\python.exe
                git:
                    commit: dc3e887748018f7ee7b57947d76051ab983413f3
                    remote: https://github.com/chrso19/Speciale_Kode.git
                gpu: NVIDIA GeForce GTX 1050 Ti
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Pascal
                      cudaCores: 768
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce GTX 1050 Ti
                      uuid: GPU-c8aba166-49dd-1470-8b6d-d1b8a72a5bc0
                host: ChristinePC
                memory:
                    total: "8432807936"
                os: Windows-10-10.0.26200-SP0
                program: c:\Users\Christine\Documents\Python\Speciale_Kode\Deep learners\GRU\GRU multivariate cyclic DK1 copy.ipynb
                python: CPython 3.10.13
                root: c:\Users\Christine\Documents\Python\Speciale_Kode\Deep learners\GRU
                startedAt: "2026-05-03T11:16:44.647507Z"
                writerId: bi1106mju8aty3v0emtdl21aw9krni53
        m: []
        python_version: 3.10.13
        t:
            "1":
                - 1
                - 5
                - 35
                - 53
            "2":
                - 1
                - 5
                - 35
                - 53
            "3":
                - 2
                - 13
                - 15
                - 16
                - 62
            "4": 3.10.13
            "5": 0.22.3
            "8":
                - 1
                - 3
            "10":
                - 20
            "12": 0.22.3
            "13": windows-amd64
batch_size:
    value: 64
combination:
    value: 29
dropout:
    value: 0
hidden_size:
    value: 32
layers:
    value: 2
learning_rate:
    value: 0.0005
max_epochs:
    value: 100
num_combinations:
    value: 96
patience:
    value: 6
predict_period:
    value: 168
price_zone:
    value: DK1
sequence_length:
    value: 24
split_setup:
    value: 2
stride:
    value: 2184
train_window:
    value: 26280
val_start:
    value: "2024-01-01 00:00:00"
val_window:
    value: 8784
